### ISSUE TITLE
[Idea] Detect RSA keys that validate for the XZ backdoor

### ISSUE THREAD

**Issue by BenBE** [badkeys/badkeys#12]
As noted in https://github.com/amlweems/xzbot#backdoor-format the format of RSA keys that can trigger the recent XZ backdoor follow a specific format, that can (for known Ed448 keys) be detected.

The attacker's key was hardcoded in the binary, thus any key that, after decrypting with ChaCha20 as in the above link and validating the signature, should potentially be marked as such a backdoored key.

Furthermore: The two explicit Ed448 keys linked in the [Ed448 patch](https://github.com/amlweems/xzbot?tab=readme-ov-file#ed448-patch) section should be marked compromised.

**Comment by hannob** [comment]
Relevant info about the RSA key format:
* https://github.com/amlweems/xzbot/blob/main/openssh.patch
* https://rya.nc/xz-valid-n.html

**Comment by hannob** [comment]
The Ed448 key is an interesting case. In principle, we can just add this to the existing lists used for the blocklist check, it would just need some minor adaptions to the blocklistmaker script in order to be able to generate the corresponding hashes from a public key.

Right now, the blocklist module only detects keys where the private key is in one of the public repos used to generate the list. This makes it unambiguous that these keys are compromised, as we can just lookup the private key.

But it seems valuable to have another list of public keys where we should consider the private key to be owned by a malicious actor, or compromised for other reasons. I guess for a case like this, it is legit, but I think I'd be hesitant to make this a big list, and I'd like to avoid having anything in there that may be controversial. (In essence: I want every detection of badkeys to be something where I can confidently say: "this is a key you do not want to use for anything".)

**Comment by hannob** [comment]
So to be clear: The second key in the link is just an example, it is an ed448 key with the private key set to zero. This works with Ed448, as the private key is just raw bytes. We can just convert that to standard PEM format and add that as another private key to the kompromat repo, I'll do a PR. (Have to check if this is a common method to have EC test keys and if it works for ECDSA as well, we may just want to have all "all-zero" private keys that there are.) I think we can handle both parts in this issue.

**Comment by hannob** [comment]
Initial attempt, standalone script for PEM private keys:
```
#!/usr/bin/python3
# (c) MIT license, Hanno Böck

import sys

from cryptography.hazmat.primitives.serialization import load_pem_private_key

with open(sys.argv[1]) as f:
    content = f.read()

key = load_pem_private_key(content.encode(), password=None)

# ASN1-encoded RSA n values are 0-prefixed, see:
# https://crypto.stackexchange.com/a/30616
n = b"\x00" + key.public_key().public_numbers().n.to_bytes(256)

a = int.from_bytes(n[0:4], byteorder="little", signed=False)
b = int.from_bytes(n[4:8], byteorder="little", signed=False)
c = int.from_bytes(n[8:16], byteorder="little", signed=False)
res = 0xFFFFFFFF & (a * b + c)
if res <= 3:
    print(f"{sys.argv[1]} xz rsa backdoor")
else:
    print(f"{sys.argv[1]} nothing")
```

I am still a bit unsure about the endianess stuff, but it works with the keys created by [xzbot.py](https://rya.nc/xz-valid-n.html). Also, I'm wondering about false positive rates, but 64 bit may be large enough that we do not need to care.

**Comment by BenBE** [comment]
Shouldn't the check for `res <= 3` be done on uint64?

**Comment by hannob** [comment]
> Shouldn't the check for `res <= 3` be done on uint64?

Thanks, good point, the line before should be
res = 0xFFFFFFFFFFFFFFFF & (a * b + c)
I truncated it to 32 bit, which would've increased the false positive rate to likely inacceptable values.

**Comment by hannob** [comment]
I have committed some initial work in a branch:
https://github.com/badkeys/badkeys/tree/xzbackdoorrsa

**Comment by hannob** [comment]
I've now merged this.

I'm still a bit unsure if it has any actual value, and if we'll ever see any such key in the wild that isn't just for testing. But well, it's a fast check, and the false positive rate is so low that we should never see any false positive by chance.
