### ISSUE TITLE
`badkeys -ts` requires paramiko, not in requirements.txt

### ISSUE THREAD

**Issue by wohali** [badkeys/badkeys#17]
As simple as the title says. Easily fixed.

**Comment by hannob** [comment]
This is kinda intentional. paramiko is only required for ssh scan mode, all the code badkeys functionality runs without it. It is referenced as an optional dependency in pyproject.toml. requirements.txt only contains the basic dependencies required for the core functionality.

(Please note that the scan modes are somewhat limited, though particularly the tls one, and I personally do not use them much, for any more serious work I would recommend using other tools to collect keys and scan them in files.)

However, I think there are a few things I should improve:
* badkeys should not fail with an exception when paramiko is not available, but print a proper error message.
* The documentation should mention the optional dependency, and also should be generally improved and mention the scan mode's limitations.

I'll leave this bug open until then.

**Comment by hannob** [comment]
Ok, documentation improved, if paramiko is not available, badkeys will print an error.

I hope this improves the situation, but I do not want to make paramiko a hard dependency. I consider the scanning modes really an optional feature, and I don't needlessly want to add dependencies.
