### ISSUE TITLE
OS-Specific Bug

### ISSUE THREAD

**Issue by dchampion** [badkeys/badkeys#4]
The following code (line 61) prevents the CLI from running on Windows: 

https://github.com/badkeys/badkeys/blob/c8cbc244f645cfcc54244fa4ea7722cd3f39ce22/badkeys/runcli.py#L59-L61

This is because `signal.SIGHUP` is not defined for non-Windows platforms. This could be fixed with a platform test, as in:
<pre>
if sys.platform != "win32":
   signal.signal(signal.SIGHUP, _sighandler)
</pre>

Or by choosing a platform-agnostic signal.

Not sure what you are trying to capture here, but it appears not to be too important from the looks of the handler :)

**Comment by hannob** [comment]
Thanks, I hadn't tested on windows before. I have now enabled windows in the CI, so we should catch these errors in the future.

I've fixed this a bit differently (catching the error) in order to make it more portable, this should now work in any case where SIGHUP is not available (e.g. other OSes): https://github.com/badkeys/badkeys/commit/c3305157ac49579e0fa86165b592b8bb73aee330

FWIW: The signal handler is there so one can get an intermediate status how many keys are already processed if one runs badkeys on a very large number of keys.
